---
expid: "000000"
input:
    dataset: ECMWF/era-interim.yaml
    bodlib: /work/ch0636/surflibs/cordex/lib_EUR-11_frac
output:
    path: /work/ch0636/g300046/ERA5/EUR-11/xa
grid:
    domain: EUR-11
    vc_table: vc_27lev.csv
