---
scheduler:
  sys: "SLURM"
  serial_template: "compute_range.py.tpl"
  batch_command: "sbatch --parsable"
  partition: "shared"
  mem_per_cpu: "7680"
  ntasks: "6"
  account: "ch0636"
  time: "14:00:00"
  job_shell: "#!/bin/sh"
  job_suffix: ".sh"
